services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin123
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=ecoStats
    ports:
      - "5432:5432"
    expose:
      - "5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin123@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "15432:80"
    depends_on:
      - db
